-- pcall(require, "settings/colorscheme")
require("settings/colourscheme")

pcall(require, "settings/ale")
pcall(require, "settings/completion")
pcall(require, "settings/lspconfig")
pcall(require, "settings/mappings")
pcall(require, "settings/movements")
pcall(require, "settings/ruby")
pcall(require, "settings/search")
pcall(require, "settings/snippets")
pcall(require, "settings/splitjoin")
pcall(require, "settings/tagbar")
pcall(require, "settings/telescope")
pcall(require, "settings/terminal")
pcall(require, "settings/treesitter")
pcall(require, "settings/ultest")
pcall(require, "settings/undotree")
