[colors]
ansi = [
  "#4B565C",
  "#E67E80",
  "#A7C080",
  "#DBBC7F",
  "#7FBBB3",
  "#D699B6",
  "#83C092",
  "#D3C6AA",
]

brights = [
  "#5C6A72",
  "#F85552",
  "#8DA101",
  "#DFA000",
  "#3A94C5",
  "#DF69BA",
  "#35A77C",
  "#DFDDC8",
]

foreground = "#D3C6AA"
background = "#2D353B"
cursor_bg = "#D3C6AA"
cursor_border = "#D3C6AA"
cursor_fg = "#2D353E"
selection_bg = "#543A48"
selection_fg = "#D3C6AA"
split = "#7FBBB3"
compose_cursor = "#E69875"
scrollbar_thumb = "#343F44"

[colors.tab_bar]
background = "#2D353B"
inactive_tab_edge = "#232A2E"

[colors.tab_bar.active_tab]
fg_color = "#232A2E"
bg_color = "#7FBBB3"

[colors.tab_bar.inactive_tab]
fg_color = "#4F585E"
bg_color = "#343F44"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#7FBBB3"
bg_color = "#343F44"

[colors.tab_bar.new_tab]
bg_color = "#2D353B"
fg_color = "#D3C6AA"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
bg_color = "#4B565C"
fg_color = "#DFDDC8"
intensity = "Bold"

[metadata]
name = "Everforest Dark"
origin_url = "https://github.com/neanias/config"
